server:
  port: 8090

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      # Routing Direction for Product Service
      routes[0]:
        id: product-service
        uri: lb://product-service
        predicates[0]: Path=/api/product/**

      # Routing Direction for Order Service
      routes[1]:
        id: order-service
        uri: lb://order-service
        predicates[0]: Path=/api/order/**

      # Routing Direction for Discovery Service
      routes[2]:
        id: discovery-service-server
        uri: http://localhost:8761
        predicates[0]: Path=/eureka/web
        filters[0]: SethPath=/

      routes[3]:
        id: inventory-service
        uri: lb://inventory-service
        predicates[0]: Path=/api/inventory/**

      routes[4]:
        id: discovery-service-static-server
        uri: http://localhost:8761
        predicates[0]: Path=/eureka/**

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

logging:
  level:
    org:
      springframework:
        cloud:
          gateway:
            route:
              RouteDefinitionLocator: INFO
            nodeValue: TRACE